### ISSUE TITLE
20200722 gsp-dba-maven-plugin 英訳レビューコメント

### ISSUE THREAD

**Issue by yoship1972** [coastland/gsp-dba-maven-plugin#141]
- 「generate-ddl」下の表が、以降の文章すべてを囲んでしまっている。（以降、レビューできず）

**Comment by mseko** [comment]
私の動作確認観点での査読に支障があったので、generate-ddlの表の崩れの部分は直しました。
他に問題ないかの確認/修正は、 @temori-tis さん、よろしくお願いします。

**Comment by yoship1972** [comment]
表崩れ修正後の文書を確認しました。問題ありません。
